baseurl = "https://ialy1595.github.io/"
title = "ialy's blog"
languageCode = "ko-KR"

disqusShortname = "ialy1595"

theme = "hello-programmer"

paginate = 4

googleAnalytics = "UA-134848712-1"

summaryLength = 30

[author]
    name = "ialy1595"
    email = "ialy12006@gmail.com"

[taxonomies]
  category = "categories"
  subcategory = "subcategories"
  tag = "tags"